Test4: Test4.cpp Schedulable.o Professor.o Group.o Classroom.o
	g++ Test4.cpp Schedulable.o Professor.o Group.o Classroom.o -o Test4

Schedulable.o: Schedulable.cpp Schedulable.h
	g++ Schedulable.cpp -c

Professor.o: Professor.cpp Professor.h
	g++ Professor.cpp -c

Group.o: Group.cpp Group.h
	g++ Group.cpp -c

Classroom.o: Classroom.cpp Classroom.h
	g++ Classroom.cpp -c