Test5: Test5.cpp Exception.o TimeException.o Time.o
	g++ Test5.cpp Exception.o TimeException.o Time.o -o Test5

Exception.o: Exception.cpp Exception.h
	g++ Exception.cpp -c

TimeException.o: TimeException.cpp TimeException.h
	g++ TimeException.cpp -c

Time.o: Time.cpp Time.h
	g++ Time.cpp -c