Test5: Test5.cpp Exception.o TimeException.o Time.o TimingException.o Timing.o Event.o
	g++ Test5.cpp Exception.o TimeException.o Time.o TimingException.o Timing.o Event.o -o Test5

Exception.o: Exception.cpp Exception.h
	g++ Exception.cpp -c

TimeException.o: TimeException.cpp TimeException.h
	g++ TimeException.cpp -c

Time.o: Time.cpp Time.h
	g++ Time.cpp -c

TimingException.o: TimingException.cpp TimingException.h
	g++ TimingException.cpp -c

Timing.o: Timing.cpp Timing.h
	g++ Timing.cpp -c

Event.o: Event.cpp Event.h
	g++ Event.cpp -c