Test6: Test6.cpp Time.o Schedulable.o Classroom.o Timing.o
	g++ Test6.cpp Time.o Schedulable.o Classroom.o Timing.o -o Test6

Time.o: Time.cpp Time.h
	g++ Time.cpp -c

Schedulable.o: Schedulable.cpp Schedulable.h
	g++ Schedulable.cpp -c

Classroom.o: Classroom.cpp Classroom.h
	g++ Classroom.cpp -c

Timing.o: Timing.cpp Timing.h
	g++ Timing.cpp -c